docRoot $VH_ROOT/html/
enableGzip 1

scriptHandler {
  add lsapi:lsphp php
}

index {
  indexFiles index.php, index.html
  autoIndex 0
  useServer 0
}

context / {
  allowBrowse 1
  location $DOC_ROOT/
  rewrite  {
    RewriteFile .htaccess
  }
}

accessLog $VH_ROOT/logs/access.log {
  logReferer 1
  logUserAgent 1
  rollingSize 10M
  keepDays 30
  compressArchive 0
}

errorlog $VH_ROOT/logs/error.log {
  logLevel DEBUG
  rollingSize 10M
  useServer 1
}
