docRoot $VH_ROOT/html/
enableGzip 1

extProcessor lsphp {
  type                    lsapi
  address                 uds://tmp/lshttpd/lsphp.sock
  maxConns                35
  env                     PHP_LSAPI_CHILDREN=35
  env                     LSAPI_AVOID_FORK=200M
  initTimeout             60
  retryTimeout            0
  persistConn             1
  respBuffer              0
  autoStart               1
  path                    /usr/local/lsws/lsphp81/bin/lsphp
  backlog                 100
  instances               1
  priority                0
  memSoftLimit            2047M
  memHardLimit            2047M
  procSoftLimit           400
  procHardLimit           500
}

scriptHandler {
  add lsapi:lsphp php
}

index {
  indexFiles index.php, index.html
  autoIndex 0
  useServer 0
}

context / {
  allowBrowse 1
  location $DOC_ROOT/
  rewrite  {
    RewriteFile .htaccess
  }
}

cache {
  enableCache             1
  expireInSeconds         180
  enablePrivateCache      1
  enablePublicCache       1
  maxCacheObjSize         10000000
  checkPrivateCache       1
  checkPublicCache        1
}

accessLog $VH_ROOT/logs/access.log {
  logReferer 1
  logUserAgent 1
  rollingSize 10M
  keepDays 30
  compressArchive 0
}

errorlog $VH_ROOT/logs/error.log {
  logLevel DEBUG
  rollingSize 10M
  useServer 1
}
