name: Deploy to AWS

on:
  push:
    branches:
     - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node (example)
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Deploy message
        run: echo "Deploying to ${{ github.ref_name }} environment"
